### ISSUE TITLE
Build issues on GNU/Linux

### ISSUE THREAD

**Issue by ghost** [flotsamarch/openlabora#1]
Gentoo ~amd64 compiled with clang, thinlto and mold; compiling openlabora just with clang and vcpkg.

Build logs: [build1.txt](https://termbin.com/w2a1), [build2.txt](https://termbin.com/a5xq). build1.txt is log of the first invocation of cmake --build, and build2.txt is the second one.

**Comment by flotsamarch** [comment]
The file which causes compilation error is temporarily removed from build by [commit](https://github.com/flotsamarch/openlabora/commit/c9a9e641d026012d169492c47fda2c9ccf113b9e). Could be fixed by including std::list, but class is not used at the moment and I'm planning to reimplement it anyway. Should no longer be an issue.
